//
// Created by hrl on 9/9/15.
//

#ifndef AVL_AVL_DEFINES_H
#define AVL_AVL_DEFINES_H

#define TREE_MAX_SIZE 1000

enum {
    TREE_OP_SUCCESS,
    TREE_INITED_ERROR,
    TREE_INIT_FAIL_ERROR,
    TREE_DEL_FAIL_ERROR,
    TREE_UNINIT_ERROR,
    TREE_INSERT_SAME_VALUE_ERROR,
    TREE_INSERT_FAIL_ERROR
};

#endif //AVL_AVL_DEFINES_H
