//
// Created by hrl on 9/11/15.
//

#ifndef AVL_SET_DEFINES_H
#define AVL_SET_DEFINES_H

enum {
    SET_OP_SUCCESS,
    SET_INITED_ERROR,
    SET_INIT_FAIL_ERROR,
    SET_UNINIT_ERROR,
    SET_SEARCH_ERROR,
    SET_INSERT_SAME_VALUE_ERROR,
    SET_INSERT_FAIL_ERROR,
    SET_DELETE_FAIL_ERROR,
    SET_INTERSECTION_ERROR,
    SET_DIFFERENCE_ERROR
};

#endif //AVL_SET_DEFINES_H
