//
// Created by hrl on 9/21/15.
//

#ifndef AVL_SNS_DEFINES_H
#define AVL_SNS_DEFINES_H

enum {
    SNS_OP_SUCCESS,
    SNS_INITED_ERROR,
    SNS_INIT_FAIL_ERROR,
    SNS_UNINIT_ERROR
};

enum {
    PEOPLE_OP_SUCCESS,
    PEOPLE_INITED_ERROR,
    PEOPLE_INIT_FAIL_ERROR,
    PEOPLE_UNINIT_ERROR
};

#endif //AVL_SNS_DEFINES_H
