//
// Created by hrl on 9/21/15.
//

#ifndef AVL_SNS_DEFINES_H
#define AVL_SNS_DEFINES_H

enum {
    SNS_OP_SUCCESS,
    SNS_IO_FAIL_ERROR,
    SNS_JSON_DECODE_FAIL_ERROR,
    SNS_JSON_ENCODE_FAIL_ERROR,
    SNS_INITED_ERROR,
    SNS_INIT_FAIL_ERROR,
    SNS_UNINIT_ERROR,
    SNS_SEARCH_ERROR,
    SNS_INSERT_FAIL_ERROR,
    SNS_DELETE_FAIL_ERROR
};

enum {
    TAG_OP_SUCCESS,
    TAG_INITED_ERROR,
    TAG_INIT_FAIL_ERROR,
    TAG_UNINIT_ERROR,
    TAG_DEL_FAIL_ERROR
};

enum {
    PEOPLE_OP_SUCCESS,
    PEOPLE_INITED_ERROR,
    PEOPLE_INIT_FAIL_ERROR,
    PEOPLE_UNINIT_ERROR,
    PEOPLE_DEL_FAIL_ERROR,
    PEOPLE_FOLLOW_FAIL_ERROR,
    PEOPLE_FRIEND_FAIL_ERROR,
    PEOPLE_TAG_FAIL_ERROR,
    PEOPLE_SEARCH_FAIL_ERROR,
    PEOPLE_CIRCLE_FAIL_ERROR
};

enum {
    PEOPLE_SHIFT_FOLLOWINGS,
    PEOPLE_SHIFT_FOLLOWERS,
    PEOPLE_SHIFT_FRIENDS,
    PEOPLE_SHIFT_INCOMING_FRIENDS,
    PEOPLE_SHIFT_TAGS
};

#endif //AVL_SNS_DEFINES_H
